spring.application.name=classbooking
spring.datasource.url=jdbc:mysql://localhost:3306/class_booking
spring.datasource.username=root
spring.datasource.password=Srinivas@4f

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
